sudo: required
services:
  - docker

before_install:
  - docker build -t karanotts/docker-fib -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true karanotts/docker-fib npm test -- --coverage

after_success:
  - docker build -t karanotts/docker-fib-client ./client
  - docker build -t karanotts/docker-fib-nginx ./nginx
  - docker build -t karanotts/docker-fib-server ./server
  - docker build -t karanotts/docker-fib-worker ./worker

  - echo "$docker_password" | docker login -i "$docker_user" --pasword-stdin
  - docker push karanotts/docker-fib-client
  - docker push karanotts/docker-fib-nginx
  - docker push karanotts/docker-fib-server
  - docker push karanotts/docker-fib-worker